/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author marcos
 */

import javax.swing.DefaultListModel;
import javax.swing.JList;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

public class VendedorGui extends javax.swing.JFrame {

    /**
     * Creates new form VendedorGui
     */

    private Vendedor vendedor;

    public VendedorGui() {
        initComponents();
        DefaultListModel d= new DefaultListModel();
        this.listaSubastas.setModel(d);
        d.addElement("ESTADO - TítuloLibro - Prezo Actual - Gañador (es)");
        d.addElement( "-------------------------------------------------------------------------------------");
    }

    public VendedorGui(Vendedor _vendedor){
        
        vendedor=_vendedor;
        initComponents();
        DefaultListModel d= new DefaultListModel();
        this.listaSubastas.setModel(d);
        d.addElement("ESTADO - TítuloLibro - Prezo Actual - Gañador (es)");
        d.addElement( "-------------------------------------------------------------------------------------");
    }

    public void mostrarInterface(){
        pack();
        super.setVisible(true);
    }


    private void engadirNovaSubasta(String _titulo, Integer _prezo){
        DefaultListModel d=  (DefaultListModel) this.listaSubastas.getModel();
        String novaEntrada= "ACTIVA - " + _titulo + " - " + _prezo + " - ";
        d.addElement(novaEntrada);
    }

    //Función para modificar a lista de subastas 
    public void modificarLista(String estado, String titulo, String prezo, String ganadores){
        DefaultListModel d=  (DefaultListModel) this.listaSubastas.getModel();

        //Recórrense todas as subastas para ver as de este libro:
        for(int i=0; i < d.getSize(); i++){
            String subasta = (String)d.get(i);
            
            if(subasta.contains(" - "+titulo+" - ")){
                //Se finalizou unha subasta, ponse o título distinto (titulo#F) para non confundir a subasta con outra do mesmo libro
                if(estado.equals("FINALIZADA"))
                    titulo+="#F";
                d.set(i, estado + " - "+titulo+" - "+prezo+" - "+ganadores);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBase = new javax.swing.JTabbedPane();
        panelLibros = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        labelTitulo1 = new javax.swing.JLabel();
        labelTitulo2 = new javax.swing.JLabel();
        titulo = new javax.swing.JTextField();
        prezo = new javax.swing.JSpinner();
        labelTitulo3 = new javax.swing.JLabel();
        incremento = new javax.swing.JSpinner();
        labelTitulo4 = new javax.swing.JLabel();
        botonEngadir = new javax.swing.JButton();

         //Acción realizada ao premer o botón
        botonEngadir.addActionListener( new ActionListener() {
            public void actionPerformed(ActionEvent ev) {
              if(titulo.getText() != null){
                    vendedor.engadirLibro(titulo.getText(), (Integer) prezo.getValue(), (Integer) incremento.getValue());
                    engadirNovaSubasta(titulo.getText(), (Integer) prezo.getValue());
                    titulo.setText("");
                }  
            }
        } );
        subastas = new javax.swing.JPanel();
        panelSubastas = new javax.swing.JScrollPane();
        listaSubastas = new javax.swing.JList<>();

        //setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new   WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                vendedor.doDelete();
            }
        } );
        setTitle("Vendedor "+vendedor.getAID().getLocalName());
        setResizable(false);

        panelBase.setBackground(new java.awt.Color(255, 255, 255));
        panelBase.setFont(new java.awt.Font("LM Roman Caps 10", 0, 15)); // NOI18N

        panelLibros.setBackground(new java.awt.Color(40, 53, 147));
        panelLibros.setFont(new java.awt.Font("LM Roman Caps 10", 0, 15)); // NOI18N

        labelTitulo.setFont(new java.awt.Font("LM Roman Caps 10", 0, 15)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        labelTitulo.setText("Título");

        labelTitulo1.setFont(new java.awt.Font("LM Roman Caps 10", 0, 15)); // NOI18N
        labelTitulo1.setForeground(new java.awt.Color(255, 255, 255));
        labelTitulo1.setText("Prezo");

        labelTitulo2.setFont(new java.awt.Font("LM Roman Caps 10", 0, 15)); // NOI18N
        labelTitulo2.setForeground(new java.awt.Color(255, 255, 255));
        labelTitulo2.setText("Incremento");

        titulo.setFont(new java.awt.Font("LM Roman Caps 10", 0, 15)); // NOI18N
        titulo.setForeground(new java.awt.Color(40, 53, 147));

        prezo.setFont(new java.awt.Font("LM Roman Caps 10", 0, 15)); // NOI18N
        prezo.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        labelTitulo3.setFont(new java.awt.Font("LM Roman Caps 10", 0, 15)); // NOI18N
        labelTitulo3.setForeground(new java.awt.Color(255, 255, 255));
        labelTitulo3.setText("€");

        incremento.setFont(new java.awt.Font("LM Roman Caps 10", 0, 15)); // NOI18N
        incremento.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        labelTitulo4.setFont(new java.awt.Font("LM Roman Caps 10", 0, 15)); // NOI18N
        labelTitulo4.setForeground(new java.awt.Color(255, 255, 255));
        labelTitulo4.setText("€");

        botonEngadir.setFont(new java.awt.Font("LM Roman Caps 10", 0, 15)); // NOI18N
        botonEngadir.setForeground(new java.awt.Color(40, 53, 147));
        botonEngadir.setText("Engadir libro");

        javax.swing.GroupLayout panelLibrosLayout = new javax.swing.GroupLayout(panelLibros);
        panelLibros.setLayout(panelLibrosLayout);
        panelLibrosLayout.setHorizontalGroup(
            panelLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLibrosLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panelLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLibrosLayout.createSequentialGroup()
                        .addComponent(incremento, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelTitulo4))
                    .addComponent(labelTitulo2)
                    .addComponent(labelTitulo1)
                    .addComponent(labelTitulo)
                    .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelLibrosLayout.createSequentialGroup()
                        .addComponent(prezo, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelTitulo3)))
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLibrosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonEngadir, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155))
        );
        panelLibrosLayout.setVerticalGroup(
            panelLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLibrosLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(labelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(labelTitulo1)
                .addGap(18, 18, 18)
                .addGroup(panelLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prezo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTitulo3))
                .addGap(53, 53, 53)
                .addComponent(labelTitulo2)
                .addGap(18, 18, 18)
                .addGroup(panelLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(incremento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTitulo4))
                .addGap(71, 71, 71)
                .addComponent(botonEngadir, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        panelBase.addTab("Engadir libros", panelLibros);

        subastas.setBackground(new java.awt.Color(40, 53, 147));
        subastas.setFont(new java.awt.Font("LM Roman Caps 10", 0, 15)); // NOI18N

        panelSubastas.setForeground(new java.awt.Color(40, 53, 147));

        listaSubastas.setFont(new java.awt.Font("LM Roman Caps 10", 0, 15)); // NOI18N
        listaSubastas.setForeground(new java.awt.Color(40, 53, 147));
        listaSubastas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "ESTADO - TítuloLibro - Prezo Actual - Gañador (es)", 
            "-------------------------------------------------------------------------------------" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        panelSubastas.setViewportView(listaSubastas);

        javax.swing.GroupLayout subastasLayout = new javax.swing.GroupLayout(subastas);
        subastas.setLayout(subastasLayout);
        subastasLayout.setHorizontalGroup(
            subastasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subastasLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(panelSubastas, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        subastasLayout.setVerticalGroup(
            subastasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subastasLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(panelSubastas, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        panelBase.addTab("Ver Subastas", subastas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBase)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBase)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VendedorGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VendedorGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VendedorGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VendedorGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VendedorGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEngadir;
    private javax.swing.JSpinner incremento;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelTitulo1;
    private javax.swing.JLabel labelTitulo2;
    private javax.swing.JLabel labelTitulo3;
    private javax.swing.JLabel labelTitulo4;
    private javax.swing.JList<String> listaSubastas;
    private javax.swing.JTabbedPane panelBase;
    private javax.swing.JPanel panelLibros;
    private javax.swing.JScrollPane panelSubastas;
    private javax.swing.JSpinner prezo;
    private javax.swing.JPanel subastas;
    private javax.swing.JTextField titulo;
    // End of variables declaration//GEN-END:variables
}
